stages:
  - test

include:
  - template: Jobs/SAST.gitlab-ci.yml

unit:
  image: python:3.10
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install pytest pytest-cov Flask
    - pip install -e .

  script:
    - pytest --cov=./ --cov-fail-under=50