stages:
  - test

include:
  - template: Jobs/SAST.gitlab-ci.yml

unit:
  image: python:3.10
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install pytest pytest-cov
    - if [ -f ./volume_calculator/requirements.txt ]; then pip install -r ./volume_calculator/requirements.txt; fi
  script:
    - pytest tests/