name: Run Tests and Check Coverage

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov Flask

    - name: Install the package
      run: |
        pip install -e .

    - name: Run tests with coverage
      run: |
        pytest --cov=./ --cov-fail-under=50
